# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'f:\Documents\Programmation\Python\combiner_video\ihm.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(642, 86)
        MainWindow.setMinimumSize(QtCore.QSize(642, 86))
        MainWindow.setMaximumSize(QtCore.QSize(642, 86))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images_ressource/logo.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton_traiter = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_traiter.setGeometry(QtCore.QRect(240, 40, 75, 23))
        self.pushButton_traiter.setObjectName("pushButton_traiter")
        self.pushButton_parcourir = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_parcourir.setGeometry(QtCore.QRect(560, 10, 75, 23))
        self.pushButton_parcourir.setObjectName("pushButton_parcourir")
        self.label_terminer = QtWidgets.QLabel(self.centralwidget)
        self.label_terminer.setGeometry(QtCore.QRect(330, 40, 51, 20))
        self.label_terminer.setObjectName("label_terminer")
        self.label_traitement = QtWidgets.QLabel(self.centralwidget)
        self.label_traitement.setGeometry(QtCore.QRect(330, 40, 131, 21))
        self.label_traitement.setObjectName("label_traitement")
        self.fileEdit_path = FileEdit(self.centralwidget)
        self.fileEdit_path.setGeometry(QtCore.QRect(10, 10, 541, 20))
        self.fileEdit_path.setObjectName("fileEdit_path")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.pushButton_parcourir, self.pushButton_traiter)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Traitement"))
        self.pushButton_traiter.setText(_translate("MainWindow", "traiter"))
        self.pushButton_parcourir.setText(_translate("MainWindow", "parcourir"))
        self.label_terminer.setText(_translate("MainWindow", "terminé !"))
        self.label_traitement.setText(_translate("MainWindow", "traitement en cours..."))
from main import FileEdit
import ressource_rc
